#!/bin/bash
# Remove eth0 from br-lan and enable NAT when DHCP succeeds

if [ "$IFACE" = "eth0" ] && [ "$AdministrativeState" = "routable" ]; then
    # Remove eth0 from bridge
    ip link set eth0 nomaster
    
    # Enable NAT masquerading for internet access
    nft add rule ip nat postrouting oifname "eth0" masquerade
fi
